### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by janbrohl** [baloise/gitopscli#139]
As this package already is [installable via pip](https://baloise.github.io/gitopscli/setup/#from-source), semver-versioned [>=1.0.0](https://github.com/baloise/gitopscli/releases),  [open source licensed](https://baloise.github.io/gitopscli/license/) - why not release on [PyPI](https://pypi.org/)?

**Comment by christiansiegel** [comment]
For us that was not a high priority yet as we only use the docker image.

Some things we might look into before releasing on PyPI:
- support _and_ tests for more than one python version (currently only 3.8 is used in the docker build/test; I think even 3.7 doesn't work at the moment)
- support windows (currently the temporary directory for git checkout is hardcoded to `/tmp`)
- add proper error message if there is no git installed (currently probably results in an ugly exception)

All of those improvements would also benefit #104.

**Comment by janbrohl** [comment]
Currently the [Setup Page](https://baloise.github.io/gitopscli/setup/#from-source) does not indicate any specific prerequisites for installing from source - would this be a new issue?

**Comment by christiansiegel** [comment]
> Currently the [Setup Page](https://baloise.github.io/gitopscli/setup/#from-source) does not indicate any specific prerequisites for installing from source - would this be a new issue?

Definetely an overlap, but I'd create a new one for now 😉

**Comment by janbrohl** [comment]
For the ``/tmp`` problem, the [tempfile](https://docs.python.org/3/library/tempfile.html) module should help.

**Comment by christiansiegel** [comment]
Closing. I don't think this is anything we'll focus on any time soon.
