### ISSUE TITLE
Why YAML?

### ISSUE THREAD

**Issue by janbrohl** [baloise/gitopscli#141]
Why is the config specified in YAML format and not in more flexible plain Python? Is this for security reasons?

**Comment by christiansiegel** [comment]
You mean the `.gitops.config.yaml` for preview envs? In what way would one need more fexibility? I agree that the first version is quite restricted. But we are working on v2 in #105..

**Comment by janbrohl** [comment]
Yes, It seems to me the discussion at #105 also adresses flexibility. Personally I don't need more flexibility as I only use code excerpts from this project anyway.
