### ISSUE TITLE
Spec for Config

### ISSUE THREAD

**Issue by janbrohl** [baloise/gitopscli#142]
I did not find a spec for the Config in this repo's docs. There seems to be some validation in https://github.com/baloise/gitopscli/blob/master/gitopscli/gitops_config.py 

With a [JSON-Schema](http://json-schema.org/) a human readable version could be generated (there are several generators) from the same source [a validator](https://python-jsonschema.readthedocs.io/en/stable/) could use. Non-JSON data can be validated this way, too.

**Comment by christiansiegel** [comment]
There is an example with some documentation in https://baloise.github.io/gitopscli/commands/create-preview/

**Comment by janbrohl** [comment]
OK.
