### ISSUE TITLE
Helm release name max length exceeded

### ISSUE THREAD

**Issue by joachimprinzbach** [baloise/gitopscli#163]
When using the default config the namespace, a namespace with 60 chars is beeing created.
This is fine for k8s, as 63 is the limit - however the helm chart release name must not exceed 53 characters:

```
Error: release name "gitops-nginx-demo-joachimprinzbach-patch-2-48f31385-preview" exceeds max length of 53
```

**Comment by joachimprinzbach** [comment]
See also: https://github.com/helm/helm/issues/6006

**Comment by joachimprinzbach** [comment]
As the namespace is equal to the heml chart release name, I would truncate it after 53 chars. The route can still be configured differently, but the default of the namespace could be changed to sth shorter (see: https://baloise.github.io/gitopscli/commands/create-preview/#gitopsconfigyaml):

**Comment by niiku** [comment]
Maybe we could shorten the hash as well to something like 3 chars?

**Comment by christiansiegel** [comment]
Maybe a new setting `namespaceMaxLength` for API version 2 that defaults to 50 (round number)?

Regarding the short 3 char hash we could add a new var SHORT_PREVIEW_ID_HASH.

**Comment by joachimprinzbach** [comment]
I would stick to 53 as a default- i really like the possibility of setting it; so we have the flexibility in the future. 

Event the length of the preview id hash could be configurable, but we should keep in mind that those things also add complexity in both the docs and the implementation.

**Comment by christiansiegel** [comment]
53 it is.

A more generic approach could also be something like `${VAR}[3]` to cut a variable after n chars 🤔

**Comment by joachimprinzbach** [comment]
I would leave it as simple as possible, YAGNI ;-)
