### ISSUE TITLE
Gitlab merge labels and parameters

### ISSUE THREAD

**Issue by epanoff** [baloise/gitopscli#193]
gitopscli creates merge requests in Gitlab without labels and parameters
https://github.com/baloise/gitopscli/blob/master/gitopscli/git_api/gitlab_git_repo_api_adapter.py#L57
I would like to add new parameter for gitopscli  for Gitlab --gitlab-labels

labels in merge request 

In documentation Gitlab it looks like
mr = project.mergerequests.create({'source_branch': 'cool_feature',
                                   'target_branch': 'main',
                                   'title': 'merge cool feature',
                                   'labels': ['label1', 'label2']})

and also I can't configure merge  parameters https://github.com/baloise/gitopscli/blob/master/gitopscli/git_api/gitlab_git_repo_api_adapter.py#L62

I would like to add parameter --gitlab-merge-parameters 
It can be            

- "merge_commit_message"
- "should_remove_source_branch"
- "merge_when_pipeline_succeeds"

for example: 
mr.merge(merge_when_pipeline_succeeds=True)

If community is ok with this suggestion, I am ready to create the PR to add this functionality (however I can create and test it only for GItlab)

Links:
[python-gitlab]: <https://python-gitlab.readthedocs.io/en/stable/gl_objects/merge_requests.html>

**Comment by joachimprinzbach** [comment]
@christiansiegel @niiku 
What do you guys think?

When I understand it correctly, each of these single params can be activated, is that correct? Otherwise a literal could be an option.

Testing from your side would be great, as we only have test instances for bitbucket and github.

**Comment by christiansiegel** [comment]
**pull request labels**
I don't think bitbucket has those, but github does. Maybe make it more generic then: `--pr-labels`?
PyGithub: https://github.com/PyGithub/PyGithub/blob/master/github/PullRequest.py#L824 (info: All PRs are also issues in the Github API, hence the issue API path)
We could then throw a "not supported" error in the bitbucket adapter if anyone tries to use the labels with it.

**merge parameters**
This seems gitlab specific enough to add an extra CLI param. Did I understand you correctly that you want to support passing a full json object containing all additional parameters to this single `--gitlab-merge-parameters` parameter? If yes, this could be done similar to the `--values` param: https://github.com/baloise/gitopscli/blob/master/gitopscli/cliparser.py#L70
