### ISSUE TITLE
Provide additional author with parameter

### ISSUE THREAD

**Issue by mikevader** [baloise/gitopscli#195]
### Context

Although the commit created by gitopscli is usually done by CI with a technical user, the actual deployment is often triggered by a user (click in the CI gui or a commit in the application repository). It could be beneficial for the history to add this user as additional author to the deployment commit.

### Solution Proposal

The deploy command would get two additional parameters for co-authors:

```
gitopscli deploy --git-provider github \
                          --username gitopscli \
                          --git-user CI-User \
                          --git-email ci@baloise.dev \
                          --co-author-name 'Mike Miller' \
                          --co-author-email mike@baloise.dev
```

The co-author values would be added to all commit messages created by gitopscli

**Comment by christiansiegel** [comment]
Do you mean a co-author trailer a the end of the commit message? (https://github.blog/2018-01-29-commit-together-with-co-authors/)

Example:
```
changed 'backend.tag' to 'foo' in values.yaml

Co-authored-by: Mike Miller <mike@baloise.dev>
```

**Comment by mikevader** [comment]
Yes exactly. [Github](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors), Bitbucket and others use this as well.

I first thought to use the `--commit-message` argument but that feels wrong. Side effect on single / multiple commits and you would loose the default commit message.
