### ISSUE TITLE
Support previews for non Helm based projects 

### ISSUE THREAD

**Issue by christiansiegel** [baloise/gitopscli#74]
`create-preview` only allows replacements in `values.yaml`. Plus, it assumes there is a `Chart.yaml` in the preview folder and replaces the `name` property. All of that is Helm specific.

Possible solution (breaking change)
- Allow to specify a filename in `gitops.config.yaml`'s `previewConfig.replace` list. This makes the replacements generic.
- Rely on the user replacing `name` in the `Chart.yaml`

**Comment by joachimprinzbach** [comment]
one option would be, to support multiple types of providers (probably the ones Argo CD supports) 
```
type: 'helm' | 'kustomize' | 'plain'
  entry: 'values.yaml' | 'myfilename.yaml'
```
