### ISSUE TITLE
Add tests for commands

### ISSUE THREAD

**Issue by christiansiegel** [baloise/gitopscli#82]
Add unit tests for every command..
..so that bugs like #80  don't happen anymore :grimacing:

**Comment by christiansiegel** [comment]
`deploy` command tests: PR #94

**Comment by joachimprinzbach** [comment]
Missing command tests:

- add_pr_comment
- create_pr_preview
- create_preview
- delete_pr_preview
- sync_apps

**Comment by christiansiegel** [comment]
add_pr_comment: PR #120
delete_pr_preview: PR #118

**Comment by christiansiegel** [comment]
sync_apps: PR #125

still missing:
- create_pr_preview
- create_preview
